"""Workspace management for session-isolated development environments."""

import shutil
from pathlib import Path
from typing import Optional


class WorkspaceManager:
    """Manages workspace directories for sessions."""

    def __init__(self, workspace_root: str = "./workspaces"):
        """Initialize workspace manager.

        Args:
            workspace_root: Root directory for all workspaces (default: ./workspaces)
        """
        self.workspace_root = Path(workspace_root).resolve()
        self.workspace_root.mkdir(parents=True, exist_ok=True)

    def init_repo(self, session_id: str, template: Optional[str] = None) -> Path:
        """Create workspace directory and initialize repo from template.

        Args:
            session_id: Unique session identifier
            template: Optional template directory to copy (default: minimal scaffold)

        Returns:
            Path to the workspace directory

        Raises:
            ValueError: If workspace already exists for this session
        """
        workspace_path = self.workspace_root / session_id

        if workspace_path.exists():
            raise ValueError(f"Workspace already exists for session {session_id}")

        # Create workspace layout (VF-111)
        workspace_path.mkdir(parents=True)
        repo_path = workspace_path / "repo"
        artifacts_path = workspace_path / "artifacts"

        repo_path.mkdir()
        artifacts_path.mkdir()

        # Initialize from template if provided
        if template:
            template_path = Path(template)
            if not template_path.exists():
                raise ValueError(f"Template directory not found: {template}")

            # Copy template contents to repo directory
            for item in template_path.iterdir():
                if item.is_file():
                    shutil.copy2(item, repo_path / item.name)
                elif item.is_dir():
                    shutil.copytree(item, repo_path / item.name)
        else:
            # Create minimal scaffold
            (repo_path / "README.md").write_text("# Project\n\nGenerated by VibeForge.\n")

        return workspace_path

    def get_workspace_path(self, session_id: str) -> Path:
        """Get the workspace directory path for a session.

        Args:
            session_id: Session identifier

        Returns:
            Path to workspace directory

        Raises:
            ValueError: If workspace doesn't exist
        """
        workspace_path = self.workspace_root / session_id
        if not workspace_path.exists():
            raise ValueError(f"Workspace not found for session {session_id}")
        return workspace_path

    def get_repo_path(self, session_id: str) -> Path:
        """Get the repo directory path for a session.

        Args:
            session_id: Session identifier

        Returns:
            Path to repo directory within workspace
        """
        return self.get_workspace_path(session_id) / "repo"

    def get_artifacts_path(self, session_id: str) -> Path:
        """Get the artifacts directory path for a session.

        Args:
            session_id: Session identifier

        Returns:
            Path to artifacts directory within workspace
        """
        return self.get_workspace_path(session_id) / "artifacts"

    def workspace_exists(self, session_id: str) -> bool:
        """Check if workspace exists for a session.

        Args:
            session_id: Session identifier

        Returns:
            True if workspace exists, False otherwise
        """
        return (self.workspace_root / session_id).exists()

    def delete_workspace(self, session_id: str):
        """Delete workspace directory for a session.

        Args:
            session_id: Session identifier
        """
        workspace_path = self.workspace_root / session_id
        if workspace_path.exists():
            shutil.rmtree(workspace_path)
